# Generated by Django 4.0.4 on 2022-04-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercore',
            name='last_ticket_request_see',
            field=models.IntegerField(default=0, verbose_name='Última Ticket Request visitada'),
        ),
    ]
