# Generated by Django 4.0.4 on 2022-05-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_regtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercore',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, verbose_name='Instagram Username'),
        ),
        migrations.AddField(
            model_name='usercore',
            name='phonenum',
            field=models.CharField(blank=True, max_length=16, verbose_name='Numero de Cel'),
        ),
    ]
