# Generated by Django 4.0.4 on 2022-04-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketrequest',
            name='total',
        ),
    ]
