# Generated by Django 4.0.4 on 2022-04-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticketrequest_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketrequest',
            name='q_tickets',
            field=models.IntegerField(verbose_name='Tickets'),
        ),
    ]
