# Generated by Django 4.0.4 on 2022-04-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticketrequest_q_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketrequest',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total'),
        ),
    ]
