# Generated by Django 4.0.4 on 2022-04-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticketrequest_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketrequest',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticketrequest',
            name='context',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='ticketrequest',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencía'), ('DEPOSIT', 'Deposíto')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketrequest',
            name='reference',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
