# Generated by Django 4.0.4 on 2022-04-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticketrequest_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketrequest',
            name='reference',
            field=models.CharField(max_length=150),
        ),
    ]
