# Generated by Django 4.0.4 on 2022-04-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_ticketrequest_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketrequest',
            name='staff',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
