# Generated by Django 4.0.4 on 2022-04-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usercore_last_ticket_request_see'),
        ('tickets', '0011_ticketrequest_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketrequest',
            name='staff',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.usercore'),
        ),
    ]
