# Generated by Django 4.0.4 on 2022-04-27 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_ticketrequest_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketrequest',
            name='staff',
        ),
    ]
