# Generated by Django 4.0.4 on 2022-04-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_ticketrequest_staff_asigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketrequest',
            name='staff_asigned',
        ),
    ]
