# Generated by Django 4.0.4 on 2022-04-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_remove_ticket_id_alter_ticket_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status_export',
            field=models.BooleanField(default=True),
        ),
    ]
