# Generated by Django 4.0.4 on 2022-04-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_ticket_qrexport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='qrexport',
        ),
    ]
