# Generated by Django 4.0.4 on 2022-04-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_remove_ticket_qrexport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketrequest',
            name='client',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketrequest',
            name='reference',
            field=models.CharField(default='none', max_length=150),
        ),
    ]
