# Generated by Django 4.0.4 on 2022-04-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_alter_ticketrequest_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comprobante',
            field=models.FileField(default='a', upload_to='uploads/comprobantes/'),
            preserve_default=False,
        ),
    ]
