# Generated by Django 4.0.4 on 2022-04-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_ticket_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='comprobante',
            field=models.FileField(default=None, upload_to='uploads/comprobantes/'),
        ),
    ]
