# Generated by Django 4.0.4 on 2022-04-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_alter_ticket_comprobante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='comprobante',
        ),
        migrations.AddField(
            model_name='ticketrequest',
            name='comprobante',
            field=models.FileField(default=None, upload_to='uploads/comprobantes/'),
        ),
    ]
