# Generated by Django 4.0.4 on 2022-04-29 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_remove_ticket_comprobante_ticketrequest_comprobante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketrequest',
            name='comprobante',
        ),
    ]
