# Generated by Django 4.0.4 on 2022-04-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_remove_ticketrequest_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketrequest',
            name='comprobante',
            field=models.FileField(default=None, upload_to='uploads/comprobantes/'),
        ),
    ]
