# Generated by Django 4.0.4 on 2022-05-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_ticketrequest_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketrequest',
            name='comprobante',
            field=models.FileField(blank=True, upload_to='uploads/comprobantes/'),
        ),
    ]
