# Generated by Django 4.0.4 on 2022-05-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_ticket_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketrequest',
            name='cash_pay',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
