# Generated by Django 4.0.4 on 2022-04-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('datetime', models.DateTimeField(verbose_name='Date, Time')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('status', models.CharField(choices=[('AN', 'Anunciado'), ('VE', 'En Venta'), ('TE', 'Venta Terminada'), ('AR', 'Archivado')], default='AN', max_length=2)),
            ],
        ),
    ]
