# Generated by Django 4.0.4 on 2022-05-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='locationmapslink',
            field=models.CharField(blank=True, max_length=300, verbose_name='Google Maps Link'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_tickets',
            field=models.IntegerField(blank=True, default=0, verbose_name='Max Tickets'),
        ),
    ]
