# Generated by Django 4.0.4 on 2022-05-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_materials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materials',
            new_name='Material',
        ),
    ]
