# Generated by Django 4.0.4 on 2022-05-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_materials_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/materials/', verbose_name='Archivo'),
        ),
    ]
