# Generated by Django 4.0.4 on 2022-05-05 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_material_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('finish', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('file1', models.FileField(upload_to='uploads/tasks/')),
                ('file2', models.FileField(upload_to='uploads/tasks/')),
                ('file3', models.FileField(upload_to='uploads/tasks/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
